"""S3-compatible object storage.

**One implementation, not four.** AWS S3, Cloudflare R2, MinIO and Backblaze B2
all speak the same API, so "add S3 / R2 / MinIO" is a single class plus an
endpoint URL in configuration. The factory's old comment suggested three
separate provider classes; that would have been three copies of this file
differing by a hostname.

  * **AWS S3** -- leave `S3_ENDPOINT_URL` unset and set `S3_REGION`.
  * **Cloudflare R2** -- endpoint `https://<account>.r2.cloudflarestorage.com`,
    region `auto`.
  * **MinIO** -- endpoint `http://localhost:9000`, any region. This is what the
    tests run against, because it needs no account and no card.
  * **Backblaze B2** -- the S3-compatible endpoint for your bucket's region.

**Why boto3 in a thread rather than aioboto3.** aioboto3 brings aiobotocore,
which pins `botocore` to a narrow range and is a well-known source of resolver
conflicts on any project that also touches the AWS SDK. What it buys is true async
network I/O, and the workload here is small files at low concurrency -- a 5 MiB
cap and ten objects per account. `asyncio.to_thread` is what `local.py` already
uses to keep the loop free, so this stays the same shape as the provider beside
it and costs a thread per call instead of a dependency constraint on everything
else.

Every failure becomes `StorageError`, so callers never import botocore. That is
the same contract `local.py` honours and the reason `ResumeService` does not
know which provider it is talking to.
"""

from __future__ import annotations

import asyncio
import logging
from pathlib import PurePosixPath
from typing import Any

from app.core.exceptions import StorageError
from app.services.storage.base import StorageService, StoredFile

logger = logging.getLogger(__name__)

# Response codes S3 uses for "no such object". `head_object` answers 404 while
# `get_object` answers NoSuchKey, and MinIO and R2 differ again in which they
# send, so both forms are treated as absence rather than as failure.
_NOT_FOUND = {"404", "NoSuchKey", "NotFound"}


class S3StorageService(StorageService):
    """Object storage over the S3 API."""

    def __init__(
        self,
        *,
        bucket: str,
        endpoint_url: str | None = None,
        region: str | None = None,
        access_key_id: str | None = None,
        secret_access_key: str | None = None,
    ) -> None:
        if not bucket:
            raise StorageError("S3 storage requires a bucket name (S3_BUCKET).")

        self._bucket = bucket
        # Built once and reused. A boto3 client is thread-safe for the calls
        # made here, and constructing one per request costs a credential
        # resolution and a TLS handshake on the upload path.
        try:
            import boto3
            from botocore.config import Config
        except ImportError as exc:  # pragma: no cover - depends on install extras
            raise StorageError(
                "boto3 is not installed; it is required for STORAGE_BACKEND=s3."
            ) from exc

        try:
            self._client: Any = boto3.client(
                "s3",
                endpoint_url=endpoint_url,
                region_name=region,
                aws_access_key_id=access_key_id,
                aws_secret_access_key=secret_access_key,
                config=Config(
                    # Two attempts, not boto3's default of five. An upload sits
                    # inside a request the user is waiting on, and the layer
                    # above already surfaces a failure rather than losing it.
                    retries={"max_attempts": 2, "mode": "standard"},
                    # MinIO and R2 both want path-style addressing; virtual-host
                    # style needs DNS per bucket, which neither provides.
                    s3={"addressing_style": "path"} if endpoint_url else {},
                ),
            )
        except Exception as exc:  # noqa: BLE001 - botocore raises its own
            raise StorageError(f"Could not build the S3 client: {exc}") from exc

    @staticmethod
    def _validate(key: str) -> str:
        """Reject keys that would be surprising as object names.

        S3 has no filesystem to escape, so this is not the traversal guard that
        `local.py` needs -- it is parity. A key is opaque and generated by this
        application; one arriving with `..` in it means something upstream is
        wrong, and the two providers should refuse it identically rather than
        one storing a literal `../` object and the other raising.
        """
        pure = PurePosixPath(key)
        if not key or pure.is_absolute() or ".." in pure.parts:
            raise StorageError("Invalid storage key.")
        return key

    async def save(self, key: str, content: bytes, content_type: str) -> StoredFile:
        self._validate(key)

        def _put() -> None:
            self._client.put_object(
                Bucket=self._bucket, Key=key, Body=content, ContentType=content_type
            )

        try:
            await asyncio.to_thread(_put)
        except Exception as exc:  # noqa: BLE001 - botocore raises its own
            # The key, never the body: the body is a resume.
            logger.error("S3 write failed", extra={"storage_key": key})
            raise StorageError("Failed to store file.") from exc
        return StoredFile(key=key, size_bytes=len(content), content_type=content_type)

    async def read(self, key: str) -> bytes:
        self._validate(key)

        def _get() -> bytes:
            response = self._client.get_object(Bucket=self._bucket, Key=key)
            return response["Body"].read()

        try:
            return await asyncio.to_thread(_get)
        except Exception as exc:  # noqa: BLE001
            if _is_missing(exc):
                raise StorageError("File not found in storage.") from exc
            raise StorageError("Failed to read file.") from exc

    async def delete(self, key: str) -> None:
        self._validate(key)

        def _delete() -> None:
            self._client.delete_object(Bucket=self._bucket, Key=key)

        try:
            # S3's delete is already idempotent -- deleting an absent key
            # succeeds -- which matches the contract `local.py` implements with
            # `missing_ok=True`.
            await asyncio.to_thread(_delete)
        except Exception as exc:  # noqa: BLE001
            if _is_missing(exc):
                return
            raise StorageError("Failed to delete file.") from exc

    async def exists(self, key: str) -> bool:
        self._validate(key)

        def _head() -> None:
            self._client.head_object(Bucket=self._bucket, Key=key)

        try:
            await asyncio.to_thread(_head)
        except Exception as exc:  # noqa: BLE001
            if _is_missing(exc):
                return False
            raise StorageError("Failed to check file.") from exc
        return True


def _is_missing(error: BaseException) -> bool:
    """Whether a botocore error means "no such object" rather than a fault.

    Read out of the response rather than by matching the exception class:
    botocore generates its error classes per service at runtime, so
    `except NoSuchKey` is not something this module can import and name.
    """
    response = getattr(error, "response", None)
    if not isinstance(response, dict):
        return False
    code = str(response.get("Error", {}).get("Code", ""))
    status = str(response.get("ResponseMetadata", {}).get("HTTPStatusCode", ""))
    return code in _NOT_FOUND or status == "404"
