"""Render an evaluation report as Markdown.

Markdown rather than a server-generated PDF, deliberately. WeasyPrint needs
cairo and pango in the image, which the slim base does not carry; ReportLab
means hand-laying-out a document and maintaining it forever. Markdown is a few
lines of string building, is readable as-is, pastes into anything, and the
browser's own print-to-PDF on the report page covers the "give me a PDF" case
with styling that already matches the app.
"""

from __future__ import annotations

from typing import Any

from app.models.evaluation_report import EvaluationReport
from app.models.interview_session import InterviewSession


def _bullets(items: Any, empty: str) -> list[str]:
    """Bullet list from a JSONB field, tolerating whatever the model produced."""
    if not isinstance(items, list):
        return [empty]
    lines = [f"- {str(item).strip()}" for item in items if isinstance(item, str) and item.strip()]
    return lines or [empty]


def render_markdown(report: EvaluationReport, session: InterviewSession) -> str:
    feedback: dict[str, Any] = report.detailed_feedback or {}

    lines: list[str] = [
        f"# Interview report — {session.title}",
        "",
    ]

    details = [
        f"**Role:** {session.target_role or 'General'}",
        f"**Type:** {session.interview_type.value.replace('_', ' ')}",
        f"**Difficulty:** {session.difficulty.value}",
    ]
    if session.completed_at:
        details.append(f"**Completed:** {session.completed_at:%Y-%m-%d %H:%M} UTC")
    lines += [" · ".join(details), ""]

    score = report.overall_score
    lines += [
        f"## Overall score: {score if score is not None else 'not scored'} / 10",
        "",
    ]

    summary = feedback.get("summary")
    if isinstance(summary, str) and summary.strip():
        lines += [summary.strip(), ""]

    lines += ["## Strengths", "", *_bullets(report.strengths, "_None identified._"), ""]
    lines += [
        "## Areas to improve",
        "",
        *_bullets(report.weaknesses, "_None identified._"),
        "",
    ]

    recommendations = feedback.get("recommendations")
    if isinstance(recommendations, list) and recommendations:
        lines += ["## Recommendations", "", *_bullets(recommendations, "_None._"), ""]

    per_question = feedback.get("per_question")
    if isinstance(per_question, list) and per_question:
        lines += ["## Question by question", ""]
        for index, entry in enumerate(per_question, start=1):
            if not isinstance(entry, dict):
                continue
            question = str(entry.get("question", "")).strip() or f"Question {index}"
            heading = f"### {index}. {question}"
            entry_score = entry.get("score")
            if isinstance(entry_score, (int, float)):
                heading += f" — {entry_score}/10"
            lines.append(heading)
            lines.append("")
            comment = str(entry.get("feedback", "")).strip()
            lines += [comment or "_No feedback given._", ""]

    lines += ["---", "", "_Generated by InterviewPilot AI._"]
    return "\n".join(lines).rstrip() + "\n"


def filename_for(session: InterviewSession) -> str:
    """A safe, descriptive download name.

    The title is user-supplied, so anything that could steer a path or break
    the Content-Disposition header is stripped rather than escaped.
    """
    # Dropped, not substituted: replacing each bad character with a hyphen
    # turns `quote"; drop` into `quote---drop`.
    kept = "".join(char for char in session.title if char.isalnum() or char in " -_")
    safe = "-".join(kept.split()) or "report"
    # Collapse any runs the title itself contributed.
    while "--" in safe:
        safe = safe.replace("--", "-")
    safe = safe.strip("-") or "report"
    return f"interview-report-{safe[:60]}.md"
