"""resume chunk search vector

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-10 19:51:55.928557
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(section, '') || ' ' || content)", persisted=True), nullable=False))
    op.create_index('ix_resume_chunks_search', 'resume_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resume_chunks_search', table_name='resume_chunks', postgresql_using='gin')
    op.drop_column('resume_chunks', 'search_vector')
    # ### end Alembic commands ###
